### ISSUE TITLE
is this dead, is not maintained 

### ISSUE THREAD

**Issue by ramiws** [int128/gradle-ssh-plugin#378]
Authfail error

**Comment by MrZeusTheCoder** [comment]
I just made PR #379 which would hopefully fix that issue. I don't know if it is a dead repo. The author seems to be active, nonetheless, so I may email him if he doesn't see the PR.

**Comment by twwwt** [comment]
@MrZeusTheCoder Did you email the author? We are having the same problem with a new Linux server that issues a host key created using an algorithm that the current version of Jssh doesn't support. If you haven't asked the author already, I can try asking him for a new release. Maybe I can also volunteer in getting it published.

**Comment by MrZeusTheCoder** [comment]
I haven't emailed him yet. I have published it to an internal server for my employer and it is working. I will let you know when I email him and I will let you know if I publish the fork to the Gradle Plugin Portal or to a personal repo.

**Comment by MrZeusTheCoder** [comment]
Correction: I realize that this is the groovy library, not Hidetake's Gradle ssh plugin. The code is all there and you can just pull the fork and publish it to a maven repo.

**Comment by twwwt** [comment]
@int128 In case you have the time to read this and react, I (and seemingly the rest of the users of this plugin) would highly appreciate if you could update both the [Groovy SSH library](https://github.com/int128/groovy-ssh) and the Gradle SSH plugin to release a new version that supports recent cipher algorithms (that are meanwhile the default on most Linux distributions). Do you think you can find time to do that. It would be a pity if both would need to be forked in order to get control and publish a new version, which would also require to use new names.

**Comment by MrZeusTheCoder** [comment]
@twwwt I just sent this email to Hidetake:

> Hello Mr. Iwata,
> 
> I recently opened a pull request on your groovy-ssh repo and another on your gradle-ssh-plugin repo. The pull requests update the repos to use a stable fork of Jsch (https://github.com/mwiede/jsch) which supports modern SSH protocols/ciphers. These PRs would fix authentication issues users are getting when trying to connect to servers running OpenSSH 7.0+.
> 
> Here are links to the PRs:
> https://github.com/int128/groovy-ssh/pull/294
> https://github.com/int128/gradle-ssh-plugin/pull/379
> 
> Is it possible for you to take a look at the pull requests and possibly make a release?
> 
> Your wonderful library has served me very well. There are unfortunately no other good options (aside from the ones that use groovy-ssh as a dependency, :D).
> 
> -Elijah

We'll see what happens. Ping me here if there is no movement and you need a public release.

**Comment by int128** [comment]
@MrZeusTheCoder @twwwt Thank you for contacting me. I appreciate your great work. I will try a new release.

**Comment by MrZeusTheCoder** [comment]
Thank you so much for taking time out to look into the PRs. So happy to be able to use this plugin again without extra complexity of a private repo. :heart:.

**Comment by int128** [comment]
This plugin was published to Gradle Plugin Portal from Bintray, but it is no longer available.
I will contact the support to reclaim this plugin.
https://plugins.gradle.org/docs/bintray

**Comment by int128** [comment]
Yes. I will try it.

**Comment by int128** [comment]
I just published a new version to https://plugins.gradle.org/plugin/org.hidetake.ssh

**Comment by arielchojnacki** [comment]
Thanks @int128 for all you work on this plugin and @MrZeusTheCoder for your contribution.
Is it expected that new version of gradle-ssh plugin is using groovy-ssh 2.8.0 (dependency in core build.gradle) and therefore jsch 0.1.53?

I would expect to use groovy-ssh 2.11.1 :)

**Comment by twwwt** [comment]
> Thanks @int128 for all you work on this plugin and @MrZeusTheCoder for your contribution. Is it expected that new version of gradle-ssh plugin is using groovy-ssh 2.8.0 (dependency in core build.gradle) and therefore jsch 0.1.53?
> 
> I would expect to use groovy-ssh 2.11.1 :)

I second that. I tried the new version 2.11.0 of the plugin today. The original problem (authentication failed) still exists.

**Comment by MrZeusTheCoder** [comment]
Seems that it was a minor typo in the release. Hopefully it can be corrected without an extra release, :/.

**Comment by MrZeusTheCoder** [comment]
@int128 is it possible to get a new release?

**Comment by twwwt** [comment]
Unless a new release has been made, I *think* there exists a workaround. It's not tested yet as there is another complication; see below.

What I have done is to upload `groovy-ssh:2.11.1` to a local artifact repository (Artifactory) that we use when building our projects. After that you can overwrite the dependency for Gradle like so:
```groovy
buildscript
{
	dependencies
	{
		classpath 'org.hidetake:core:2.11.0'
		classpath 'org.hidetake:groovy-ssh:2.11.1'
	}
}
```
and apply the plugin as usual:
```groovy
plugins
{
	id 'org.hidetake.ssh'
}
```
However, the other complication is that `org.hidetake:groovy-ssh:2.11.1` transitively depends on `com.github.mwiede:jsch:0.2.5` (compile-time). `jsch` requires Java >=16. Which means that if you want to run the plugin in a Gradle project where you need to compile sources for earlier versions (e.g., Java 11 in my case), you need to use Gradle toolchains support in order to get this working; i.e., run Gradle with, for instance, Java 17 and configure it to compile for Java 11.

**Comment by MrZeusTheCoder** [comment]
Good for you for finding that @twwwt . Certainly better than any of the other options so far, so it's good to have progress, :D.

**Comment by int128** [comment]
I just published a new release as https://github.com/int128/gradle-ssh-plugin/releases/tag/2.11.1

**Comment by MrZeusTheCoder** [comment]
:partying_face: :tada: !!!

**Comment by twbecker** [comment]
I must be missing something...I see groovy-ssh 2.11.1 has been release but I can't find it in any repo:
```

**Comment by MrZeusTheCoder** [comment]
:face_with_spiral_eyes: it's referencing it from the private maven repo of the `groovy-ssh` Github repo: https://github.com/int128/gradle-ssh-plugin/commit/1b6fe0842194435ed7a11e969742aab6a8c6fa16#diff-56752320f0e842c005a324b5b6511c83be46c0d3c4a6b5b61f20267effa11a9aR10 . This could possibly remedied with `api` instead of `implementation` (I forget exactly how that all works), or @int128 could deploy it to a repo.

**Comment by twbecker** [comment]
The metadata for the plugin properly references groovy-ssh 2.11.1, it apparently was just never published to a public repo. @int128 can you do that?

**Comment by int128** [comment]
I thought GitHub Packages was public but actually it is private. 
We need to publish it to Maven Central. I will try it.

**Comment by MrZeusTheCoder** [comment]
@int128 If you have any trouble going through the process of getting on Maven Central, feel free to contact me. I have gone through the process before for work. It could be a bit easier, :/.

**Comment by MrZeusTheCoder** [comment]
Additionally, if you need artifacts temporarily hosted on Maven Central while you get access, I am sure my employer will be willing to host it with our account.

**Comment by int128** [comment]
I could publish an artifact to Nexus of OSSRH from my local. I will try it from GitHub Actions as https://github.com/int128/groovy-ssh/pull/306.

**Comment by int128** [comment]
Luckily, I found my PGP key from my local and could published one.
I confirmed the artifact is published as https://central.sonatype.com/artifact/org.hidetake/groovy-ssh/2.11.2/overview.

Thank you for your pull request. I will merge it and release a new version.

**Comment by int128** [comment]
I published Gradle SSH Plugin 2.11.2.
https://plugins.gradle.org/plugin/org.hidetake.ssh

**Comment by MrZeusTheCoder** [comment]
I tested this release and I can confirm that it at least worked once, :). Also I think the above discourse has made it thoroughly clear that "this is not dead, is maintained".

**Comment by int128** [comment]
I really appreciate your great help. Closing this issue.
